export default {
    configList:[
        {
            patternConfigs:[
                {
                    params:[
                        {ang:4,l:1},
                        {ang:5,l:1},
                        {ang:0,l:2},
                        {ang:1,l:1},
                        {ang:3,l:2}
                    ]
                },
                {
                    params:[
                        {ang:5,l:1},
                        {ang:0,l:1},
                        {ang:1,l:2},
                        {ang:2,l:1},
                        {ang:4,l:2}
                    ]
                },
                {
                    params:[
                        {ang:0,l:1},
                        {ang:1,l:1},
                        {ang:2,l:2},
                        {ang:3,l:1},
                        {ang:5,l:2}
                    ]
                },
                {
                    params:[
                        {ang:4,l:1},
                        {ang:5,l:1},
                        {ang:0,l:2},
                        {ang:1,l:1},
                        {ang:3,l:2}
                    ]
                },
                {
                    params:[
                        {ang:4,l:1},
                        {ang:5,l:1},
                        {ang:0,l:2},
                        {ang:1,l:1},
                        {ang:3,l:2}
                    ]
                },
                {
                    params:[
                        {ang:4,l:1},
                        {ang:5,l:1},
                        {ang:0,l:2},
                        {ang:1,l:1},
                        {ang:3,l:2}
                    ]
                },
                
            ]
        },
        {
            patternConfigs:[
                {
                    params:[
                        {
                            ang:4,
                            l:1
                        },
                        {
                            ang:4,
                            l:1
                        },
                        {
                            ang:4,
                            l:1
                        },
                        {
                            ang:4,
                            l:1
                        },
                        {
                            ang:4,
                            l:1
                        },
                        {
                            ang:4,
                            l:1
                        },
                    ]
                }
            ]
        },
        
    ]
}